### ISSUE TITLE
Can not build the lastest version: failed to select a version for `futures-channel-preview`

### ISSUE THREAD

**Issue by jimliang** [telegram-rs/telegram-bot#134]
```toml
[dependencies]
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot" }
```

```bash
error: failed to select a version for `futures-channel-preview`.
    ... required by package `hyper v0.13.0-a.0 (https://github.com/hyperium/hyper#79c32f89)`
    ... which is depended on by `hyper-tls v0.3.2 (https://github.com/hyperium/hyper-tls.git?rev=4b9ed650add2471e04de90bb888146f89468dd08#4b9ed650)`
    ... which is depended on by `telegram-bot v0.6.3 (F:\git\telegram-bot\lib)`
    ... which is depended on by `jim-telegrambot v0.1.0 (F:\ideaProject\telegrambot)`
versions that meet the requirements `^0.3.0-alpha.18` are: 0.3.0-alpha.18
```
