### ISSUE TITLE
Fix the README and examples

### ISSUE THREAD

**Issue by mclucario** [telegram-rs/telegram-bot#187]
I am new to Rust and I would like to help to contribute to this project. I recently tried to use this library but the examples don't seem to work. Where do I get the necessary up to date infos to create some new examples?

**Comment by ndelvalle** [comment]
This would be awesome!

**Comment by andywswan** [comment]
simple.rs works for me with this in Cargo.toml:
```
[dependencies]
futures-preview = "=0.3.0-alpha.19"
tokio = "=0.2.0-alpha.6"
telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }
```

**Comment by kedodrill** [comment]
To get the `simple.rs` example to work for me, I had to use these dependencies:

```TOML
[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }
```
